"""create farmer profile and farm tables

Revision ID: cd83f6534134
Revises: fed1742c7973
Create Date: 2026-06-27 21:16:49.189895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd83f6534134'
down_revision: Union[str, Sequence[str], None] = 'fed1742c7973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('village', sa.String(length=100), nullable=False),
    sa.Column('profile_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('farms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_profile_id', sa.UUID(), nullable=False),
    sa.Column('farm_name', sa.String(length=100), nullable=False),
    sa.Column('land_area', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('land_unit', sa.Enum('ACRE', 'HECTARE', 'BIGHA', name='landunitenum'), nullable=True),
    sa.Column('soil_type', sa.Enum('CLAY', 'SANDY', 'LOAMY', 'SILTY', 'BLACK', 'RED', 'LATERITE', 'ALLUVIAL', 'MOUNTAIN', 'UNKNOWN', name='soiltypeenum'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_profile_id'], ['farmer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farms')
    op.drop_table('farmer_profiles')
    # ### end Alembic commands ###
