"""create weather cache table

Revision ID: dc7dcb4de359
Revises: 235802a55798
Create Date: 2026-07-11 07:55:02.446330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7dcb4de359'
down_revision: Union[str, Sequence[str], None] = '235802a55798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_provider_request_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.Enum('WEATHER_API', 'OPEN_METEO', name='weatherproviderenum'), nullable=False),
    sa.Column('provider_version', sa.String(length=30), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_provider_fetched', 'weather_provider_request_logs', ['fetched_at'], unique=False)
    op.create_index('idx_provider_name', 'weather_provider_request_logs', ['provider_name'], unique=False)
    op.create_index('idx_provider_status', 'weather_provider_request_logs', ['status_code'], unique=False)
    op.create_table('weather_advisories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('advisory_type', sa.Enum('RAIN', 'IRRIGATION', 'HEAT', 'FROST', 'WIND', 'HUMIDITY', 'DISEASE', 'WEATHER_SUMMARY', 'TEMPERATURE', name='advisorytypeenum'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='advisoryseverityenum'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_advisory_created', 'weather_advisories', ['created_at'], unique=False)
    op.create_index('idx_advisory_farm', 'weather_advisories', ['farm_id'], unique=False)
    op.create_index('idx_advisory_read', 'weather_advisories', ['is_read'], unique=False)
    op.create_index('idx_advisory_severity', 'weather_advisories', ['severity'], unique=False)
    op.create_table('weather_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('weather_type', sa.Enum('CURRENT', 'FORECAST', name='weathertypeenum'), nullable=False),
    sa.Column('provider_name', sa.Enum('WEATHER_API', 'OPEN_METEO', name='weatherproviderenum'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('weather_data', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'weather_type', name='uq_weather_cache_farm_type')
    )
    op.create_index('idx_weather_cache_expiry', 'weather_cache', ['expires_at'], unique=False)
    op.create_index('idx_weather_cache_farm', 'weather_cache', ['farm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_weather_cache_farm', table_name='weather_cache')
    op.drop_index('idx_weather_cache_expiry', table_name='weather_cache')
    op.drop_table('weather_cache')
    op.drop_index('idx_advisory_severity', table_name='weather_advisories')
    op.drop_index('idx_advisory_read', table_name='weather_advisories')
    op.drop_index('idx_advisory_farm', table_name='weather_advisories')
    op.drop_index('idx_advisory_created', table_name='weather_advisories')
    op.drop_table('weather_advisories')
    op.drop_index('idx_provider_status', table_name='weather_provider_request_logs')
    op.drop_index('idx_provider_name', table_name='weather_provider_request_logs')
    op.drop_index('idx_provider_fetched', table_name='weather_provider_request_logs')
    op.drop_table('weather_provider_request_logs')
    # ### end Alembic commands ###
